run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - gosimple
    - unused
    - ineffassign
    - typecheck
    - gofmt
    - goimports
    - misspell
    - revive
    - unconvert

linters-settings:
  goimports:
    local-prefixes: github.com/conn-castle/agent-layer
  revive:
    rules:
      - name: exported

issues:
  exclude-use-default: false
